platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

target 'TimeSlice' do

end


post_install do |installer| installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|

        end
    end
end
